## Scraping data dari Playstore

In [1]:
pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 1.8 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [2]:
from google_play_scraper import reviews, Sort
import pandas as pd

# Ganti dengan ID aplikasi yang ingin di-scrape
app_id = "com.mobile.legends"

# Scraping ulasan
reviews_list, _ = reviews(
    app_id,
    lang="id",  # Bahasa Indonesia
    country="id",  # Negara Indonesia
    sort=Sort.MOST_RELEVANT,  # Urutkan berdasarkan yang terbaru
    count=10000  # Jumlah ulasan yang ingin diambil
)

In [3]:
# Menyimpan ulasan dalam file CSV
import csv

with open('mobile_legends_reviews1.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Review'])  # Menulis header kolom
    for review in reviews_list:
        writer.writerow([review['content']])  # Menulis konten ulasan ke dalam file CSV

app_reviews_df = pd.DataFrame(reviews_list)
app_reviews_df.shape
app_reviews_df.head()
app_reviews_df.to_csv('mobile_legends_reviews1.csv', index=False, encoding="utf-8")

## Data Loading

In [4]:
# Membuat DataFrame dari hasil scrapreview
app_reviews_df = pd.DataFrame(reviews_list)

# Menghitung jumlah baris dan kolom dalam DataFrame
jumlah_ulasan, jumlah_kolom = app_reviews_df.shape

In [5]:
# Menampilkan lima baris pertama dari DataFrame app_reviews_df
app_reviews_df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,a88d9682-8a77-433a-825c-493070197e3d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Aku turunkan rating bintang nya. Tolong pelaku...,1,5129,1.9.48.10373,2025-03-08 02:16:20,None,NaT,1.9.48.10373
1,97add647-794f-42eb-a02e-fd58f5a424a5,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Game nya diperbarui lagi lah! Enak enak main r...,1,1090,1.9.48.10373,2025-03-03 09:17:47,None,NaT,1.9.48.10373
2,c1482b0d-47a9-422f-a30c-df75e8624192,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Kondisi lag saat di tengah game sering banget ...,1,293,1.9.48.10373,2025-03-10 14:35:22,None,NaT,1.9.48.10373
3,a6efbddf-25c1-4de5-bf04-7fe3109e0b96,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Montonnnnn, gimana sih. Gak sekali dua kali pa...",3,652,1.9.48.10373,2025-03-04 10:49:14,None,NaT,1.9.48.10373
4,7f35b682-b6f4-40ec-a3bd-41b9e8e5f3f8,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Sama saja kasih skin tapi dibuat kalah terus. ...,1,1699,1.9.48.10373,2025-02-26 14:09:53,None,NaT,1.9.48.10373

In [6]:
# Menampilkan informasi tentang DataFrame app_reviews_df
app_reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              10000 non-null  object
 1   userName              10000 non-null  object
 2   userImage             10000 non-null  object
 3   content               10000 non-null  object
 4   score                 10000 non-null  int64
 5   thumbsUpCount         10000 non-null  int64
 6   reviewCreatedVersion  9997 non-null   object
 7   at                    10000 non-null  datetime64[ns]
 8   replyContent          421 non-null    object
 9   repliedAt             421 non-null    datetime64[ns]
 10  appVersion            9997 non-null   object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 859.5+ KB

In [10]:
# Menghapus baris duplikat dari DataFrame clean_df
df_cleaned = app_reviews_df.drop_duplicates()

# Menghitung jumlah baris dan kolom dalam DataFrame clean_df setelah menghapus duplikat
jumlah_ulasan_setelah_hapus_duplikat, jumlah_kolom_setelah_hapus_duplikat = df_cleaned.shape

In [11]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              10000 non-null  object
 1   userName              10000 non-null  object
 2   userImage             10000 non-null  object
 3   content               10000 non-null  object
 4   score                 10000 non-null  int64
 5   thumbsUpCount         10000 non-null  int64
 6   reviewCreatedVersion  9997 non-null   object
 7   at                    10000 non-null  datetime64[ns]
 8   replyContent          421 non-null    object
 9   repliedAt             421 non-null    datetime64[ns]
 10  appVersion            9997 non-null   object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 859.5+ KB

In [12]:
# Simpan ke file CSV
df_cleaned.to_csv("mobile_legends_reviews_cleaned1.csv", index=False, encoding="utf-8")

In [13]:
df_cleaned.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,a88d9682-8a77-433a-825c-493070197e3d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Aku turunkan rating bintang nya. Tolong pelaku...,1,5129,1.9.48.10373,2025-03-08 02:16:20,None,NaT,1.9.48.10373
1,97add647-794f-42eb-a02e-fd58f5a424a5,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Game nya diperbarui lagi lah! Enak enak main r...,1,1090,1.9.48.10373,2025-03-03 09:17:47,None,NaT,1.9.48.10373
2,c1482b0d-47a9-422f-a30c-df75e8624192,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Kondisi lag saat di tengah game sering banget ...,1,293,1.9.48.10373,2025-03-10 14:35:22,None,NaT,1.9.48.10373
3,a6efbddf-25c1-4de5-bf04-7fe3109e0b96,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Montonnnnn, gimana sih. Gak sekali dua kali pa...",3,652,1.9.48.10373,2025-03-04 10:49:14,None,NaT,1.9.48.10373
4,7f35b682-b6f4-40ec-a3bd-41b9e8e5f3f8,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Sama saja kasih skin tapi dibuat kalah terus. ...,1,1699,1.9.48.10373,2025-02-26 14:09:53,None,NaT,1.9.48.10373